version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: "./gradlew bootRun"
    volumes:
      - .:/app/
      - ~/.gradle/:/root/.gradle/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/postgres?user=postgres
  shell:
    build: .
    command: bash
    volumes:
      - .:/app/
      - ~/.gradle/:/root/.gradle/
